competitors:
  - Champion
  - Jackson
  - Meiko
  - CMA
  - Noble
  - ADS
  - Moyer Diebel
  - Douglas
  - LVO

lines:
  - Door Type
  - Undercounter
  - Prep Washer
  - Rack Conveyor
  - Flight Type
