Champion:
  Door Type:
    - https://www.championindustries.com/our-products/door-type/
  Undercounter:
    - https://www.championindustries.com/our-products/undercounter-dishwashers/
  Prep Washer:
    - https://www.championindustries.com/our-products/pot-pan/
  Rack Conveyor:
    - https://www.championindustries.com/our-products/rack-conveyors/
  Flight Type:
    - https://www.championindustries.com/our-products/flight-machines/

Jackson:
  Door Type:
    - https://www.jacksonwws.com/categories/high-temp-door-types/
    - https://www.jacksonwws.com/categories/low-temp-door-types/
  Undercounter:
    - https://www.jacksonwws.com/categories/undercounters/
  Prep Washer:
    []  # N/A
  Rack Conveyor:
    - https://www.jacksonwws.com/categories/conveyors-good-better-best/
  Flight Type:
    - https://www.jacksonwws.com/products/flightstar/

Meiko:
  Door Type:
    - https://www.meiko.com/en-us/products/commercial-dishwashers/door-type-dishwashers
  Undercounter:
    - https://www.meiko.com/en-us/products/commercial-dishwashers/undercounter-dishwashers
  Prep Washer:
    - https://www.meiko.com/en-us/products/commercial-dishwashers/pot-and-pan-washers
  Rack Conveyor:
    - https://www.meiko.com/en-us/products/commercial-dishwashers/rack-conveyor-dishwashers
  Flight Type:
    - https://www.meiko.com/en-us/products/commercial-dishwashers/flight-type-dishwashers

CMA:
  Door Type:
    - https://cmadishmachines.com/cma-product-category/upright-high-temperature-commercial-dishwashers/
    - https://cmadishmachines.com/cma-product-category/upright-low-temperature-dishwashers/
  Undercounter:
    - https://cmadishmachines.com/cma-product-category/undercounter-low-temperature-dishwashers/
    - https://cmadishmachines.com/cma-product-category/undercounter-high-temperature-dishwashers/
  Prep Washer:
    - https://cmadishmachines.com/cma-product-category/pot-washer/
  Rack Conveyor:
    - https://cmadishmachines.com/cma-product-category/conveyor-dishwashers/
  Flight Type:
    []  # N/A

Noble:
  Door Type:
    - https://www.webstaurantstore.com/4317/single-rack-dishwashers-and-double-rack-dishwashers.html?vendor=Noble-Warewashing
  Undercounter:
    - https://www.webstaurantstore.com/4321/under-counter-dishwashers.html?vendor=Noble-Warewashing
  Prep Washer:
    - https://www.webstaurantstore.com/4321/under-counter-dishwashers.html?vendor=Noble-Warewashing
  Rack Conveyor:
    - https://www.webstaurantstore.com/4313/conveyor-dishwashers.html?vendor=Noble-Warewashing
  Flight Type:
    []  # N/A

ADS:
  Door Type:
    - https://www.americandish.com/dish-machines/
  Undercounter:
    - https://www.americandish.com/dish-machines/
  Prep Washer:
    - https://www.americandish.com/dish-machines/    
  Rack Conveyor:
    - https://www.americandish.com/dish-machines/
  Flight Type:
    []  # N/A

Moyer Diebel:
  Door Type:
    - https://www.moyerdiebel.com/door-type/
  Undercounter:
    - https://www.moyerdiebel.com/undercounter-dishwashers/
  Prep Washer:
    []  # Moyer Diebel has no prep washer
  Rack Conveyor:
    - https://www.moyerdiebel.com/rack-conveyors/
  Flight Type:
    []  # Moyer Diebel has no flight line

Douglas:
  Door Type:
    []   # Not applicable
  Undercounter:
    []   # Not applicable
  Prep Washer:
    - https://www.dougmac.com/industrial-washers/commercial-pot-pan-and-utensil-washers/
  Rack Conveyor:
    []   # Not applicable
  Flight Type:
    []   # Not applicable

LVO:
  Door Type:
    []  # N/A
  Undercounter:
    []  # N/A
  Prep Washer:
    - https://www.lvomfg.com/site/product-category/washers/pan-washers/panwasherstyle/panwasherfrontload/
  Rack Conveyor:
    []  # N/A
  Flight Type:
    []  # N/A
