
Champion:
  Door Type: []
  Undercounter: [] 
  Prep Washer: []
  Rack Conveyor: []
  Flight Type: []

Jackson:
  Door Type: []
  Undercounter: [] 
  Prep Washer: []
  Rack Conveyor: []
  Flight Type: []

Meiko:
  Door Type: []
  Undercounter: [] 
  Prep Washer: []
  Rack Conveyor: []
  Flight Type: []

CMA:
  Door Type: []
  Undercounter: [] 
  Prep Washer: []
  Rack Conveyor: []
  Flight Type: []

Noble:
  Door Type: []
  Undercounter: [] 
  Prep Washer: []
  Rack Conveyor: []
  Flight Type: []

ADS:
  Door Type: []
  Undercounter: [] 
  Prep Washer: []
  Rack Conveyor: []
  Flight Type: []

Moyer Diebel:
  Door Type: []
  Undercounter: [] 
  Prep Washer: []
  Rack Conveyor: []
  Flight Type: []

Douglas:
  Door Type: []
  Undercounter: [] 
  Prep Washer: []
  Rack Conveyor: []
  Flight Type: []

LVO:
  Door Type: []
  Undercounter: [] 
  Prep Washer: []
  Rack Conveyor: []
  Flight Type: []
